In [46]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE

In [47]:
df = pd.read_csv("D:\Data since\Epsilon AI\DSP\Mid_project_1\Online Sales Dataset\online_sales_dataset_cleaned.csv")
df_copy = df.copy()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\sony0\AppData\Local\Temp\ipykernel_11212\4068013395.py:1: SyntaxWarning: invalid escape sequence '\D'
  df = pd.read_csv("D:\Data since\Epsilon AI\DSP\Mid_project_1\Online Sales Dataset\online_sales_dataset_cleaned.csv")

### copy the DS to a new one

In [48]:
df_copy.to_csv("D:\Data since\Epsilon AI\DSP\Mid_project_1\Online Sales Dataset\online_sales_dataset_cleaned_ML.csv", index=False)
df_copy

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\sony0\AppData\Local\Temp\ipykernel_11212\1790831237.py:1: SyntaxWarning: invalid escape sequence '\D'
  df_copy.to_csv("D:\Data since\Epsilon AI\DSP\Mid_project_1\Online Sales Dataset\online_sales_dataset_cleaned_ML.csv", index=False)

,invoice_num,stock_code,description,quantity,unit_price,customer_id,country,discount,payment_method,shipping_cost,...,warehouse_location,order_priority,order_year,order_month,order_weekday,order_hour,is_return,net_quantity,is_refund,sales
0,221958,SKU_1964,White Mug,38,1.71,37039,Australia,0.47,Bank Transfer,10.790000,...,London,Medium,2020,1,Wednesday,0,False,38,False,64.98
1,771155,SKU_1241,White Mug,18,41.25,19144,Spain,0.19,paypall,9.510000,...,Rome,Medium,2020,1,Wednesday,1,False,18,False,742.50
2,231932,SKU_1501,Headphones,49,29.11,50472,Germany,0.35,Bank Transfer,23.030000,...,Berlin,High,2020,1,Wednesday,2,True,49,False,1426.39
3,465838,SKU_1760,Desk Lamp,14,76.68,96586,Netherlands,0.14,paypall,11.080000,...,Rome,Low,2020,1,Wednesday,3,False,14,False,1073.52
4,359178,SKU_1386,USB Cable,30,68.11,-999,United Kingdom,1.00,Bank Transfer,18.710545,...,Berlin,Medium,2020,1,Wednesday,4,True,30,True,2043.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,354083,SKU_1562,Blue Pen,25,70.92,51445,Spain,0.20,Credit Card,8.960000,...,Berlin,Medium,2025,9,Friday,1,True,25,False,1773.00
49778,296698,SKU_1930,USB Cable,7,51.74,28879,United States,0.23,Bank Transfer,23.550000,...,Amsterdam,Low,2025,9,Friday,2,False,7,False,362.18
49779,177622,SKU_1766,Office Chair,43,85.25,21825,Portugal,0.20,Bank Transfer,16.260000,...,London,High,2025,9,Friday,3,False,43,False,3665.75
49780,701213,SKU_1602,Notebook,48,39.64,43199,United Kingdom,0.31,paypall,28.560000,...,London,Medium,2025,9,Friday,4,False,48,False,1902.72
49781,772215,SKU_1832,White Mug,30,38.27,53328,France,0.10,Credit Card,9.130000,...,Rome,Low,2025,9,Friday,5,False,30,False,1148.10

### comparing the value count of is_refund column

In [50]:
df_copy['is_refund'].value_counts()

is_refund
False    47293
True      2489
Name: count, dtype: int64

### droping the unwanted columns

In [51]:
df_copy.drop(['invoice_num', 'stock_code', 'description', 'quantity',
       'customer_id', 'country',  
       'category', 'sales_channel', 'return_status', 'shipment_provider',
       'warehouse_location',  'order_year', 'order_month',
       'order_weekday', 'order_hour', 'is_return', 'net_quantity',
       'sales'], axis=1, inplace=True)

In [65]:
df_copy.head(5)

,unit_price,discount,shipping_cost,order_priority,is_refund,payment_method_Credit Card,payment_method_paypall
0,1.71,0.47,10.790000,2,0,0,0
1,41.25,0.19,9.510000,2,0,0,1
2,29.11,0.35,23.030000,3,0,0,0
3,76.68,0.14,11.080000,1,0,0,1
4,68.11,1.00,18.710545,2,1,0,0

In [53]:
df_copy['order_priority'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

### handling categorical columns using label encoder

In [54]:
encoder = {
    'Low': 1,
    'Medium': 2,
    'High': 3
}
df_copy['order_priority'] = df_copy['order_priority'].map(encoder)

In [55]:
encoder_1 = {False: 0, True: 1}
df_copy['is_refund'] = df_copy['is_refund'].map(encoder_1)

In [56]:
df_copy.head(2)

,unit_price,discount,payment_method,shipping_cost,order_priority,is_refund
0,1.71,0.47,Bank Transfer,10.79,2,0
1,41.25,0.19,paypall,9.51,2,0

### handling cetegorical data using onehotencoder

In [57]:
df_copy = pd.get_dummies(df_copy,columns=['payment_method'], drop_first=True,dtype='int')
df_copy.head(2)

,unit_price,discount,shipping_cost,order_priority,is_refund,payment_method_Credit Card,payment_method_paypall
0,1.71,0.47,10.79,2,0,0,0
1,41.25,0.19,9.51,2,0,0,1

### split the input and the output

In [58]:
x = df_copy.drop(['is_refund'], axis=1)
y = df_copy['is_refund']

### split the data to train and test

In [59]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

### scaling

In [60]:
scaler = StandardScaler()
x_scaled_train = scaler.fit_transform(x_train)
x_scaled_test = scaler.transform(x_test)

In [61]:
x_scaled_train = pd.DataFrame(x_scaled_train, columns=x_train.columns)
x_scaled_test = pd.DataFrame(x_scaled_test, columns=x_test.columns)

In [62]:
smote = SMOTE()
x_train_resampled, y_train_resampled = smote.fit_resample(x_scaled_train, y_train)

In [ ]:
x_train_resampled = pd.DataFrame(x_train_resampled, columns=x_scaled_train.columns)
x_train_resampled.head(2)

,unit_price,discount,shipping_cost,order_priority,payment_method_Credit Card,payment_method_paypall
0,0.562807,-0.935143,-0.823150,-0.001446,1.422241,-0.705230
1,0.310377,-0.144824,-0.402526,-1.226723,-0.703116,1.417977

In [64]:
y_train_resampled.value_counts()

is_refund
0    37834
1    37834
Name: count, dtype: int64